# Generated by Django 3.2.3 on 2021-07-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoEnTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=99, null=True)),
                ('cantidad', models.IntegerField(blank=True, max_length=13, null=True)),
                ('fechaDeOrden', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['fechaDeOrden'],
            },
        ),
    ]
