# Generated by Django 3.2.4 on 2021-06-18 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=registration.models.custom_upload_to)),
                ('bio', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre', models.CharField(blank=True, max_length=99, null=True)),
                ('apellido', models.CharField(blank=True, max_length=99, null=True)),
                ('birthday', models.CharField(blank=True, max_length=13, null=True)),
                ('telefono', models.CharField(blank=True, max_length=99, null=True)),
                ('calle', models.CharField(blank=True, max_length=99, null=True)),
                ('numero', models.CharField(blank=True, max_length=99, null=True)),
                ('colonia', models.CharField(blank=True, max_length=99, null=True)),
                ('cp', models.CharField(blank=True, max_length=99, null=True)),
                ('esEmpresa', models.BooleanField(blank=True, null=True)),
                ('nombreEmpresa', models.CharField(blank=True, max_length=99, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
